apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/architect-demos/apigateway:v0.1
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: NEW_ID_SERVICE_ADDR
            value: "newidservice:50052"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: ClusterIP
  selector:
    app: apigateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-external
spec:
  type: LoadBalancer
  selector:
    app: apigateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
