apiVersion: apps/v1
kind: Deployment
metadata:
  name: newidservice
spec:
  selector:
    matchLabels:
      app: newidservice
  template:
    metadata:
      labels:
        app: newidservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/architecture-demos/newid:v0.1
        ports:
        - containerPort: 50052
        env:
        - name: PORT
          value: "50052"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: newidservice
spec:
  type: ClusterIP
  selector:
    app: newidservice
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
