// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: remainder.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Remainder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainderId int64  `protobuf:"varint,1,opt,name=remainderId,proto3" json:"remainderId,omitempty"`
	Remainder   string `protobuf:"bytes,2,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *Remainder) Reset() {
	*x = Remainder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Remainder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remainder) ProtoMessage() {}

func (x *Remainder) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remainder.ProtoReflect.Descriptor instead.
func (*Remainder) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{0}
}

func (x *Remainder) GetRemainderId() int64 {
	if x != nil {
		return x.RemainderId
	}
	return 0
}

func (x *Remainder) GetRemainder() string {
	if x != nil {
		return x.Remainder
	}
	return ""
}

type GetNewIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainder string `protobuf:"bytes,1,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *GetNewIdRequest) Reset() {
	*x = GetNewIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewIdRequest) ProtoMessage() {}

func (x *GetNewIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewIdRequest.ProtoReflect.Descriptor instead.
func (*GetNewIdRequest) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewIdRequest) GetRemainder() string {
	if x != nil {
		return x.Remainder
	}
	return ""
}

type GetNewIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainder *Remainder `protobuf:"bytes,1,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *GetNewIdResponse) Reset() {
	*x = GetNewIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewIdResponse) ProtoMessage() {}

func (x *GetNewIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewIdResponse.ProtoReflect.Descriptor instead.
func (*GetNewIdResponse) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{2}
}

func (x *GetNewIdResponse) GetRemainder() *Remainder {
	if x != nil {
		return x.Remainder
	}
	return nil
}

var File_remainder_proto protoreflect.FileDescriptor

var file_remainder_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x22, 0x4b, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22,
	0x2f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x22, 0x4c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x32, 0x62,
	0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x49, 0x64, 0x12, 0x20, 0x2e,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x72, 0x65, 0x6d, 0x69, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remainder_proto_rawDescOnce sync.Once
	file_remainder_proto_rawDescData = file_remainder_proto_rawDesc
)

func file_remainder_proto_rawDescGZIP() []byte {
	file_remainder_proto_rawDescOnce.Do(func() {
		file_remainder_proto_rawDescData = protoimpl.X.CompressGZIP(file_remainder_proto_rawDescData)
	})
	return file_remainder_proto_rawDescData
}

var file_remainder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_remainder_proto_goTypes = []interface{}{
	(*Remainder)(nil),        // 0: remainderprotos.Remainder
	(*GetNewIdRequest)(nil),  // 1: remainderprotos.GetNewIdRequest
	(*GetNewIdResponse)(nil), // 2: remainderprotos.GetNewIdResponse
}
var file_remainder_proto_depIdxs = []int32{
	0, // 0: remainderprotos.GetNewIdResponse.remainder:type_name -> remainderprotos.Remainder
	1, // 1: remainderprotos.ReminderService.GetNewId:input_type -> remainderprotos.GetNewIdRequest
	2, // 2: remainderprotos.ReminderService.GetNewId:output_type -> remainderprotos.GetNewIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_remainder_proto_init() }
func file_remainder_proto_init() {
	if File_remainder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remainder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Remainder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remainder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remainder_proto_goTypes,
		DependencyIndexes: file_remainder_proto_depIdxs,
		MessageInfos:      file_remainder_proto_msgTypes,
	}.Build()
	File_remainder_proto = out.File
	file_remainder_proto_rawDesc = nil
	file_remainder_proto_goTypes = nil
	file_remainder_proto_depIdxs = nil
}
